### ISSUE TITLE
Fails to build on Ubuntu

### ISSUE THREAD

**Issue by shaynevanasperen** [adamralph/minver#171]
When building my project on Ubuntu, I get the following error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-8e0b172' or one of its dependencies. In order to helpdiagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-8e0b172: cannot open shared object file: No such file or directory
     at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
     at LibGit2Sharp.Core.NativeMethods.LoadNativeLibrary()
     at LibGit2Sharp.Core.NativeMethods..cctor()
     --- End of inner exception stack trace ---
     at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)
     at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
     at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter)
     at MinVer.Lib.RepositoryEx.TryCreateRepo(String path, Repository& repository) in C:\projects\min-ver\MinVer.Lib\RepositoryEx.cs:line 16
     at MinVer.Program.GetVersion(String path, String tagPrefix, MajorMinor range, String buildMetadata, Verbosity level) in C:\projects\min-ver\minver-cli\Program.cs:line 80
     at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in C:\projects\min-ver\minver-cli\Program.cs:line 34
     at MinVer.Program.Main(String[] args) in C:\projects\min-ver\minver-cli\Program.cs:line 27
  Aborted (core dumped)
```

**Comment by adamralph** [comment]
@shaynevanasperen thanks for raising this. Please see the [FAQ](https://github.com/adamralph/minver#why-does-minver-fail-with-systemtypeinitializationexception).

**Comment by slang25** [comment]
Hey @shaynevanasperen, you could also try referencing `LibGit2Sharp` version `0.26.0-preview-0070` as a private dependency, they have done some reduce the native dependencies in that version. I can't guarantee it will work, I'm more curious that anything.

**Comment by slang25** [comment]
Try now with beta2 @shaynevanasperen
