### ISSUE TITLE
MinVer CLI Fails On macOS

### ISSUE THREAD

**Issue by khalidabuhakmeh** [adamralph/minver#318]
## Version(s)

MinVer 2.0

## To reproduce

1. run `dotnet tool install --global minver-cli --version 2.0.0` in command window
2. Go to git directory of project
3. type `minver`

## Expected behavior

Work.

## Actual behaviour

![image](https://user-images.githubusercontent.com/228256/71547547-59079800-296f-11ea-9c83-2e25ed131cb4.png)

<details>

```console
Unhandled Exception: System.Exception: Failed to run Git. Git may not be installed on the system. ---> System.ComponentModel.Win32Exception: No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 32
   --- End of inner exception stack trace ---
   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 36
   at MinVer.Lib.Repository.TryCreateRepo(String workDir, Repository& repository, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Repository.cs:line 21
   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 36
   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, MajorMinor minMajorMinor, String buildMeta, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 9
   at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in /home/runner/work/minver/minver/minver-cli/Program.cs:line 62
   at MinVer.Program.Main(String[] args) in /home/runner/work/minver/minver/minver-cli/Program.cs:line 31
```

</details>

## Additional context

on macOS Catalina. The `Win32Exception` might have something to do with it :smile:.

**Comment by khalidabuhakmeh** [comment]
So, found out the solution. Turns out that the version of `git` provided by Catalina is broken some how.

```console
➜ git version
git version 2.21.0 (Apple Git-122.2)
```

after running `brew install git` I get a newer version of `git`.

```console
➜ brew install git
➜ git version
git version 2.24.1
```

All the tests pass and now everything is good.

BTW, maybe MinVer shouldn't throw a `Win32Exception` a `MinVerException` might be more applicable in this case.

**Comment by adamralph** [comment]
@khalidabuhakmeh thanks for raising this.

> Unhandled Exception: System.Exception: Failed to run Git. Git may not be installed on the system. ---> System.ComponentModel.Win32Exception: No such file or directory

This means that `git` is not available in your PATH. I guess there is indeed something wrong with the out of the box git installation on your system. The version of git is not the problem. The exception is being thrown because git cannot be found at all. I guess that, when you update git, it fixes the installation at the same time so that `git` is available on your PATH.

> BTW, maybe MinVer shouldn't throw a `Win32Exception` a `MinVerException` might be more applicable in this case.

MinVer is already throwing a `System.Exception` with the custom message "Failed to run Git. Git may not be installed on the system.". The `System.ComponentModel.Win32Exception` is the _inner_ exception thrown by `Interop.Sys.ForkAndExecProcess()`.

**Comment by khalidabuhakmeh** [comment]
Yeah, a lot of the default macOS dependencies are jacked out of the box: Ruby, Git, etc. I normally do a fresh install of all of them, but must have missed git this time around (just did a system refresh).

Thanks :) ✌️
